version: '3'

# This project only works if everything is ran from docker
# when you want to simply call kafka from your java project
# you need to change 
#       ADVERTISED_HOST = localhost
#       --zookeeper localhost:9092
#       kafkaService=localhost:9092"

services:
# policy image still needs to be adjusted to be able to find kafka location ( e.g. kafka:9092 )
  policy:
    image: nndcdc/policy:3
    container_name: policy
    ports:
      - "8085:8085"
    command: ["kafkaService=kafka:9092"]
    links:
        - kafka

  regeling:
    image: nndcdc/regeling:3
    ports:
      - "8081:8081"
    command: ["policyService=event",
              "policyURL=http://policy:8085/v1/policies/newSchemeCreated",
              "kafkaService=kafka:9092"]
    links:
      - kafka

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "regelingAangemaakt:1:1, regelingAangepast:1:1, polisAangemaakt:1:1, polisAangpast:1:1"
    links:
      - zookeeper
